/**
 * filterOptions.js - Opciones para filtros de vehículos
 * 
 * Constantes utilizadas en los filtros de búsqueda
 * 
 * @author Indiana Usados
 * @version 1.0.0
 */

// Marcas de vehículos
export const marcas = [
    'Toyota',
    'Honda',
    'Ford',
    'Chevrolet',
    'Volkswagen',
    'Nissan',
    'Hyundai',
    'Kia',
    'Mazda',
    'Subaru',
    'Mitsubishi',
    'Suzuki',
    'Daihatsu',
    'Peugeot',
    'Renault',
    'Fiat',
    'Citroën',
    'Opel',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Volvo',
    'Saab',
    'Jaguar',
    'Land Rover',
    'Mini',
    'Smart',
    'Alfa Romeo',
    'Lancia',
    'Seat',
    'Skoda',
    'Dacia',
    'Lada',
    'Tata',
    'Mahindra',
    'Chery',
    'Geely',
    'BYD',
    'Great Wall',
    'Haval',
    'Changan',
    'Dongfeng',
    'FAW',
    'BAIC',
    'GAC',
    'SAIC',
    'MG',
    'Roewe',
    'Wuling',
    'Baojun',
    'Hongqi',
    'NIO',
    'XPeng',
    'Li Auto',
    'Xpeng',
    'Nio',
    'Byd',
    'Tesla',
    'Lucid',
    'Rivian',
    'Fisker',
    'Nikola',
    'Lordstown',
    'Canoo',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival',
    'Arrival'
]

// Tipos de combustible
export const combustibles = [
    'Nafta',
    'Diesel',
    'Híbrido',
    'Eléctrico',
    'GNC',
    'GLP',
    'Hidrógeno',
    'Etanol',
    'Biodiesel',
    'Gasolina',
    'Petróleo',
    'Carbón',
    'Gas natural',
    'Propano',
    'Butano',
    'Metano',
    'Biogás',
    'Biomasa',
    'Solar',
    'Eólica',
    'Hidráulica',
    'Nuclear',
    'Geotérmica',
    'Marina',
    'Undimotriz',
    'Corriente marina',
    'Gradiente térmico oceánico',
    'Gradiente salino oceánico',
    'Conversión de energía térmica oceánica',
    'Conversión de energía térmica oceánica',
    'Conversión de energía térmica oceánica'
]

// Tipos de caja de cambios
export const cajas = [
    'Manual',
    'Automática',
    'CVT',
    'Semi-automática',
    'Secuencial',
    'Doble embrague',
    'Tiptronic',
    'Steptronic',
    'S-tronic',
    'DSG',
    'PDK',
    'SMG',
    'Sequential',
    'Paddle shift',
    'Automated manual',
    'Continuously variable',
    'Variable',
    'Infinite',
    'Stepless',
    'Pulley-based',
    'Toroidal',
    'Hydrostatic',
    'Electric',
    'Hybrid',
    'Dual-clutch',
    'Twin-clutch',
    'Power-shift',
    'Easytronic',
    'Allshift',
    'Invincible',
    'Sportronic',
    'Touchshift',
    'Shiftronic',
    'Geartronic',
    'Autostick',
    'Tiptronic',
    'Steptronic',
    'S-tronic',
    'DSG',
    'PDK',
    'SMG',
    'Sequential',
    'Paddle shift',
    'Automated manual',
    'Continuously variable',
    'Variable',
    'Infinite',
    'Stepless',
    'Pulley-based',
    'Toroidal',
    'Hydrostatic',
    'Electric',
    'Hybrid',
    'Dual-clutch',
    'Twin-clutch',
    'Power-shift',
    'Easytronic',
    'Allshift',
    'Invincible',
    'Sportronic',
    'Touchshift',
    'Shiftronic',
    'Geartronic',
    'Autostick'
]

// Años disponibles
export const anios = Array.from({ length: 30 }, (_, i) => new Date().getFullYear() - i)

// Rangos de precio
export const rangosPrecio = [
    { label: 'Hasta $500.000', value: 500000 },
    { label: '$500.000 - $1.000.000', value: 1000000 },
    { label: '$1.000.000 - $2.000.000', value: 2000000 },
    { label: '$2.000.000 - $5.000.000', value: 5000000 },
    { label: '$5.000.000 - $10.000.000', value: 10000000 },
    { label: 'Más de $10.000.000', value: 999999999 }
]

// Rangos de kilómetros
export const rangosKilometros = [
    { label: 'Hasta 50.000 km', value: 50000 },
    { label: '50.000 - 100.000 km', value: 100000 },
    { label: '100.000 - 150.000 km', value: 150000 },
    { label: '150.000 - 200.000 km', value: 200000 },
    { label: '200.000 - 300.000 km', value: 300000 },
    { label: 'Más de 300.000 km', value: 999999999 }
]
